# -*- coding: utf-8 -*-
"""Interquartile Range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsYacPiVTcbajOba6BQWvbcjMjk2UC57
"""

import numpy as np
import matplotlib.pyplot as plt

data = [10, 12, 15, 18, 20, 22, 25, 28, 30]

q1 = np.percentile(data, 25)
q2 = np.percentile(data, 50)  # Median
q3 = np.percentile(data, 75)

iqr = q3 - q1

print("Q1 =", q1)
print("Median =", q2)
print("Q3 =", q3)
print("IQR =", iqr)

plt.figure(figsize=(6,4))
plt.boxplot(data)
plt.title("Box Plot showing Interquartile Range (IQR)")
plt.ylabel("Values")
plt.grid(True)

plt.show()